######################## default configuration ####################
baseURL = "https://getistio.io/"
title = "GetIstio"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
# disableLanguages = ["fr"] # disable language from here
enableRobotsTXT = true
hasCJKLanguage = true
paginate = "6"

# hugo outputs
[outputs]
home = [ "HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"
page = "/"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
attributes = ""
page = "/"

[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
attributes = ""
page = "/"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/turbolinks/turbolinks.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/search.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
attributes = ""
page = "/"

[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
attributes = ""
page = "search/"

[[params.plugins.js]]
link = "plugins/search/mark.js"
attributes = ""
page = "search/"

[[params.plugins.js]]
link = "plugins/search/search-page.js"
attributes = ""
page = "search/"


############## English navigation ###############

# main menu
[[Languages.en.menu.main]]
name = "Docs"
url = "/getistio-cli/"
weight = 1

[[Languages.en.menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[Languages.en.menu.main]]
name = "Community"
url = "/community"
weight = 3

[[Languages.en.menu.main]]
name = "Training"
url = "https://academy.tetrate.io"
weight = 4

[[Languages.en.menu.main]]
name = "Partners"
url = "/ecosystem-partners/"
weight = 5

[[Languages.en.menu.main]]
name = "GetEnvoy"
url = "https://www.getenvoy.io/"
weight = 6

# footer menu

#[[Languages.en.menu.footer]]
#name = "Github"
#url = "https://github.com/tetratelabs/"
#weight = 3

#################### default parameters ################################
[params]
logo = "images/getistio-logo-h-white.png"
# Meta data
description = "GetIstio project website, an open source Istio distribution"
author = "Tetrate"
sitename = "GetIstio"
twitter = "@tetrateio"
github = "https://github.com/tetratelabs/getistio"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
# [[params.nav_button]]
# style = "outline" # available style: solid, outline
# label = "changelog"
# link = "changelog"

[[params.nav_button]]
style = "solid" # available style: solid, outline
label = "Download"
link = "/download"

############################# social site ########################
[[params.social]]
title = "website"
icon = "ti-world" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/tetrateio"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/tetrateio"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://www.github.com/tetratelabs"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/tetrate/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en/"
weight = 1
# copyright
copyright = "Copyright &copy; 2021 Tetrate"

# banner
[Languages.en.banner]
title = "GetIstio Documentation"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/banner.jpg"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = "false"
  label = "Submit a ticket"
  link = "contact"

################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh"
weight = 2
# copyright
copyright = "Copyright &copy; 2021 Tetrate"

# banner
[Languages.zh.banner]
title = "GetIstio 文档"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/banner.jpg"

# call to action
[Languages.zh.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.zh.call_to_action.button]
  enable = "false"
  label = "Submit a ticket"
  link = "contact"

############## Chinese navigation ###############

# main menu
[[Languages.zh.menu.main]]
name = "文档"
url = "/getistio-cli/"
weight = 1

[[Languages.zh.menu.main]]
name = "博客"
url = "/blog/"
weight = 2

[[Languages.zh.menu.main]]
name = "社区"
url = "/community/"
weight = 3

[[Languages.zh.menu.main]]
name = "培训"
url = "https://academy.tetrate.io"
weight = 4

[[Languages.zh.menu.main]]
name = "伙伴"
url = "/ecosystem-partners/"
weight = 5

[[Languages.zh.menu.main]]
name = "GetEnvoy"
url = "https://www.getenvoy.io/"
weight = 6
