[[redirects]]
from = "https://getistio.io"
to = "https://istio.tetratelabs.io"
status = 301
force = true

[[redirects]]
from = "https://www.getistio.io"
to = "https://istio.tetratelabs.io"
status = 301
force = true

# Redirect latest version of download.sh from getmesh repo
[[redirects]]
from = "/getmesh/install.sh"
to = "https://raw.githubusercontent.com/tetratelabs/getmesh/main/site/install.sh"
force = true
status = 302

# Redirect latest version of manifest.json from getmesh repo
[[redirects]]
from = "/getmesh/manifest.json"
to = "https://raw.githubusercontent.com/tetratelabs/getmesh/main/site/manifest.json"
force = true
status = 302

# Redirect to the cloudsmith binary
[[redirects]]
 from = "https://istio.tetratelabs.io/getmesh/files/*"
 to = "https://dl.getistio.io/public/raw/files/:splat"
 status = 200
 force = true
